services:
  db:
    container_name: ${COMPOSE_PROJECT_NAME}.postgres
    build:
      context: .
    image: ${COMPOSE_PROJECT_NAME}/postgres
    ports:
      - 5432:5432
    volumes:
      - db-prisma-test:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}


volumes:
  db-prisma-test:

